name: yiisoft-data-db
services:
  php:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./../src:/code/src
      - ./../tests:/code/tests
      - ./../composer.json:/code/composer.json
      - ./../phpunit.xml.dist:/code/phpunit.xml.dist
    command: tail -F anything
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mssql:
        condition: service_healthy
      oracle:
        condition: service_healthy
  mysql:
    image: mysql:9
    ports:
      - "3306:3306"
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: data-db-test
      MYSQL_USER: yii
      MYSQL_PASSWORD: 'q1w2e3r4'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uyii" ]
      interval: 5s
      timeout: 5s
      retries: 20
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: data-db-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    user: root
    volumes:
      - mssql-data:/var/opt/mssql/data
      - mssql-log:/var/opt/mssql/log
      - mssql-secrets:/var/opt/mssql/secrets
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: Y
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1" -b -C -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 100
      start_period: 10s
  oracle:
    build:
      context: oracle
    ports:
      - "1521:1521"
    volumes:
      - ./oracle/init.sql:/docker-entrypoint-initdb.d/init.sql
      - oracle-data:/opt/oracle/oradata
    environment:
      ORACLE_PASSWORD: sys_user_password
      APP_USER: my_user
      APP_USER_PASSWORD: password_i_should_change
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 5s
      start_interval: 5s
volumes:
  mssql-data:
  mssql-log:
  mssql-secrets:
  oracle-data:
